server:
  port: 8080
spring:
  application:
    name: seckill_demo
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://39.100.194.182:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      pool-prepared-statements: false
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 10000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
      time-between-eviction-runs-millis: 600000
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  mapper-locations: classpath*:mapper/*.xml
logging:
  config: classpath:logback-spring.xml

